---
- hosts: server
  gather_facts: no

  tasks:
  - name: test local action
    local_action:
      module: command hostname
    register: rc

  - name: test local action
    local_action:
      module: debug
      var: rc.stdout

  - name: generate random password
    local_action:
      module: command openssl rand -hex 3
    register: random_password_rc
    run_once: true

  - name: set password variable
    set_fact:
      mysql_root_password: "{{ random_password_rc.stdout }}"

  - name: record generated password!
    debug:
      msg: "----------- [{{ mysql_root_password }}] ------------"
    run_once: true
