---
- hosts: server
  become: yes

  pre_tasks:
  - name: generate random password
    command: openssl rand -hex 3
    register: random_password_rc

  - name: set password variable
    set_fact:
      mysql_root_password: "{{ random_password_rc.stdout }}"

  tasks:
  - include_role:
      name: geerlingguy.mysql
    vars:
      mysql_root_password_update: yes
      mysql_root_password: "{{ inventory_hostname }}-1314"

  post_tasks:
  - name: record generated password!
    debug:
      msg: "----------- [{{ mysql_root_password }}] ------------"
