- hosts: 127.0.0.1
  connection: local
  gather_facts: smart

  vars:
    ansible_python_interpreter: python3

  tasks:
  - name: generate random password
    python_expr:
      expr: "''.join(random.choices(candidates, k=8))"
      vars:
        candidates: abcdefgABCDEFG123456_+-=
      imports:
        - random
    register: rc

  - name: output random password
    debug: var=rc.result

  - name: check file existence
    python_expr:
      expr: os.path.exists(file)
      vars:
        file: /dev/null
      imports:
        - os.path
    register: rc

  - name: fail if /dev/null not exists
    fail:
    when: not rc.result
