---
- hosts: server
  become: yes

  pre_tasks:
  - name: generate random password
    set_fact:
      mysql_root_password: "{{ 10 | random_password(candidates='abcd1234') }}"

  roles:
  - role: geerlingguy.mysql
    vars:
      mysql_root_password_update: yes

  post_tasks:
  - name: record generated password!
    debug:
      msg: "----------- [{{ mysql_root_password }}] ------------"
